item {
  id: 1
  name: 'chess'
}
item {
  id: 2
  name: 'rect'
}
item {
  id: 3
  name: 'circle'
}
item {
  id: 4
  name: 'music'
}
item {
  id: 5
  name: 'shop'
}
item {
  id: 6
  name: 'magic'
}
item {
  id: 7
  name: 'waste'
}